#!/bin/sh
if [ "$1" = "inc" ]; then
	amixer set Master 1%+
	amixer set Master unmute
elif [ "$1" == "toggle" ]; then
	amixer set Master toggle
else
	amixer set Master 1%-
	amixer set Master unmute
fi
spid=`cat /tmp/ram/dwmStat.pid`
kill -USR1 $spid
pkill -P $spid sleep
