#!/bin/sh
vol="${2:-5}"
case "$1" in
	mictog) pactl set-source-mute @DEFAULT_SOURCE@ toggle ;;

	toggle) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;

	dec) pactl set-sink-volume @DEFAULT_SINK@ -"$vol"% ;;

	inc) pactl set-sink-volume @DEFAULT_SINK@ +"$vol"%
	pactl set-sink-mute @DEFAULT_SINK@ off ;;
esac
spid=`cat /tmp/ram/dwmStat.pid`
kill -USR1 $spid
pkill -P $spid sleep
