#!/bin/sh
vol="${2:-5}"
case "$1" in
	toggle) amixer -c 1 set Master toggle ;;

	dec) amixer -c 1 set Master "$vol"%- ;;

	inc) amixer -c 1 set Master "$vol"%+
	amixer set Master unmute ;;
esac
dunst_vol
