#!/bin/dash

s1="  "; s2="  "
cn=""; ci=""; cw=""; ce=""
#cs="";
cs="";

echo $$ > /tmp/ram/dwmStat.pid

while :; do
	current_mus=$(mpc current --wait)

	notify-send "Now Playing" "$current_mus"

	kill -USR2 $$
	pkill -P $$ sleep
done &

uMpd () {
	mpd="$ci$s1「 ♪  $(mpc current)  」$s2"
	if [ "$mpd" = "$ci$s1「 ♪    」$s2" ]; then
		mpd="$cn"
	fi
	updateRoot=1
}
uMpd

trap "sMpd=1;" USR2
sMpd=0


uTemp () {
	temp=`sensors | grep "Package id 0:" | sed -e "s/+//" -e "s/ /\n/g" -e "s/\.0//" | grep -v "+" | grep °C`
	temp="$cs$s1$temp$s2"
	updateRoot=1
}
iTemp=1
uTemp


uBat () {
	for i in /sys/class/power_supply/BAT?/ ; do
		if [ -e $i ]; then
			bat=`cat $i/capacity`
			
			if grep 'Discharging' $i/status > /dev/null; then
			bat="⇣ $bat""%"
			else
			bat="⚡ $bat""%"
			fi
			tbat="$cs$s1$bat$s2"
		fi
	done
	[ -z "$tbat" ] && tbat="$cs"
	updateRoot=1
}
iBat=1
uBat


uDate () {
#	date=`date +'%a %d/%m %H:%M'`
	date=`date +'%a %H:%M'`
	date="$cs$s1$date$s2"
	updateRoot=1
}
iDate=30
uDate


while true; do
	time=`date +%s`


	if [ $sMpd -eq "1" ]; then
		printf "mpd.."
		uMpd
		sMpd=0
	fi


	if [ "$(($time % $iTemp))" -eq "0" ]; then
		printf "temp.."
		uTemp
	fi


	if [ "$( expr $time % $iBat )" -eq "0" ]; then
		printf "bat.."
		uBat
	fi


	if [ "$(($time % $iDate))" -eq "0" ]; then
		printf "time.."
		uDate
	fi

	if [ "$updateRoot" -eq "1" ]; then
		xsetroot -name "$mpd$temp$tbat$date"
		updateRoot=0
	fi

	sleep 1
done
